language: node_js

node_js: 0.1

script:
- "se-interpreter selenium/interpreter.json"

addons:
  sauce_connect: true

env:
  global:
  - SAUCE_USERNAME: testyantra1
  - ACCESS_KEY: f81a366e-8252-4af4-a850-9cf37d3bc9e2

notifications:
  email:
    recipients:
      - rethesh.ks@testyantra.com
    on_success: always
    on_failure: always

branches:
  only:
    - master

cache:
  directories:
  - node_modules